name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Build and Bundle
      run: |
        chmod +x bundle.sh
        ./bundle.sh
        tar -cvzf macro-macos.tar.gz target/release/macro

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Macro.dmg
          macro-macos.tar.gz
        draft: false
        prerelease: ${{ contains(github.ref, 'beta') }}
